In [27]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from IPython.core.display import SVG
from sklearn import tree

In [28]:
df = pd.read_csv('https://stepik.org/media/attachments/course/4852/training_mush.csv')
df.head()

cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0          2            0          3        1     5                1   
1          2            0          4        0     5                1   
2          2            0          3        0     2                1   
3          0            0          3        0     5                1   
4          2            3          3        1     5                1   

   gill-spacing  gill-size  gill-color  stalk-shape  ...  \
0             0          0           9            1  ...   
1             0          1          10            0  ...   
2             0          0           7            0  ...   
3             1          0           2            0  ...   
4             0          0          10            1  ...   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       3                       7          0           2   
1                       7                       4          0           2   
2                       0                       4          0           2   
3                       7                       7          0           2   
4                       3                       6          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  class  
0            1          4                  3           5        0      0  
1            1          0                  7           4        0      1  
2            1          2                  1           5        1      1  
3            2          4                  7           3        1      0  
4            1          4                  2           5        0      0  

[5 rows x 23 columns]

In [29]:
X_train = df.drop('class', axis = 1)
y_train = df['class']

In [30]:
clf = RandomForestClassifier(random_state=0)

In [31]:
parameters = {'n_estimators': range(10,50,10),
              'max_depth' : range(1,12,2),
              'min_samples_leaf' : range(1,7),
              'min_samples_split' : range(2,9,2)}

In [32]:
grid_search_cv = GridSearchCV(estimator=clf, param_grid=parameters, cv=3)

In [33]:
grid_search_cv.fit(X_train, y_train)

GridSearchCV(cv=3, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False, random_state=0,
                                   

In [34]:
grid_search_cv.best_params_

{'max_depth': 9,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 10}

In [35]:
best_clf = grid_search_cv.best_estimator_

In [36]:
best_clf.feature_importances_

array([0.00257742, 0.00312957, 0.02177298, 0.07010933, 0.18837641,
       0.        , 0.0808402 , 0.06846076, 0.10386114, 0.00756262,
       0.10379322, 0.03180155, 0.04829594, 0.01768932, 0.00625335,
       0.        , 0.0108812 , 0.0139101 , 0.07072612, 0.08356419,
       0.04378343, 0.02261118])

In [37]:
X_test = pd.read_csv('https://stepik.org/media/attachments/course/4852/testing_mush.csv')

In [38]:
predictions = best_clf.predict(X_test)
predictions

array([0, 0, 1, ..., 1, 0, 1], dtype=int64)

In [39]:
sum(predictions)

976

In [40]:
# New dataset
df_new = pd.read_csv('https://stepik.org/media/attachments/course/4852/invasion.csv')
df_new.head()

class  g_reflection  i_reflection       speed  brightness  \
0  transport      2.190672      6.716633   62.168208    0.347465   
1  transport      3.453276      8.995909   62.994707    0.590094   
2  transport      2.432994      6.938691   62.245807    0.329288   
3    fighter      6.083763      3.019459   18.474555    0.174738   
4    fighter     12.876769      2.452950  195.805771    0.150446   

   time_of_observance     volume  
0              158221  44.932446  
1              385972  41.568300  
2              446482  40.123467  
3              210125  11.384865  
4               23109  11.328806

In [41]:
X_train_new = df_new.drop('class', axis = 1)
y_train_new = df_new['class']

In [42]:
clf_new = RandomForestClassifier()

In [43]:
clf_new.fit(X_train_new, y_train_new)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [44]:
X_test_new  = pd.read_csv('https://stepik.org/media/attachments/course/4852/operative_information.csv')

In [50]:
predictions_new = clf_new.predict(X_test_new)
predictions_new

array(['fighter', 'transport', 'transport', ..., 'transport', 'fighter',
       'transport'], dtype=object)

In [47]:
import collections

In [51]:
collections.Counter(predictions)
unique, counts = np.unique(predictions_new, return_counts=True)
dict(zip(unique, counts))

{'cruiser': 230, 'fighter': 675, 'transport': 595}

In [53]:
pd.Series(predictions_new).value_counts()

fighter      675
transport    595
cruiser      230
dtype: int64

In [54]:
clf_new.feature_importances_

array([0.21363959, 0.0681665 , 0.12742302, 0.27555925, 0.00084795,
       0.31436369])